upgrade dependency: java^0.6.0 => java^0.8.0
since I failed to install java@0.6.1:

------------------------------------------------
npm ERR! Linux 4.11.6-101.fc24.x86_64
npm ERR! argv "/opt/node-v6.10.3-linux-x64/bin/node" "/usr/bin/npm" "install"
npm ERR! node v6.10.3
npm ERR! npm  v3.9.5
npm ERR! code ELIFECYCLE

npm ERR! java@0.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.6.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs java
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

------------------------------------------------

> java@0.6.1 install /home/panzy/workspace/nodejdbc/node_modules/java
> node-gyp rebuild

make: Entering directory '/home/panzy/workspace/nodejdbc/node_modules/java/build'
  CXX(target) Release/obj.target/nodejavabridge_bindings/src/java.o
In file included from ../src/java.h:9:0,
                 from ../src/java.cpp:1:
../../nan/nan.h:590:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^~~~~~~~~~~~~~~~~~
../../nan/nan.h:590:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^~